/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // Premium Spice Colors
        'primary-red': '#DC2626',
        'primary-red-dark': '#991B1B',
        'primary-red-light': '#EF4444',
        'turmeric': '#EAB308',
        'turmeric-dark': '#CA8A04',
        'turmeric-light': '#FACC15',
        'saffron': '#F59E0B',
        'saffron-dark': '#D97706',
        'saffron-light': '#FCD34D',
        'dark-brown': '#78350F',
        'dark-brown-light': '#92400E',
        'cream': '#FFF7ED',
        'cream-light': '#FFFBF0',
        'cream-dark': '#FEF3C7',
        // Existing colors kept for compatibility
        'spice-red': '#8B1E1E',
        'spice-red-dark': '#6B1515',
        'spice-red-light': '#A62D2D',
        'gold': '#D9A441',
        'gold-light': '#E8B860',
        'brown': '#3E2723',
        'brown-light': '#5D4037',
        'beige': {
          50: '#FEFCF8',
          100: '#FDF9F3',
          200: '#F8F4EC',
          300: '#F0E6D2',
        },
      },
      fontFamily: {
        'sans': ['Poppins', 'system-ui', 'sans-serif'],
        'serif': ['Playfair Display', 'serif'],
        'luxury': ['Playfair Display', 'serif'],
      },
      fontSize: {
        'xs': ['0.75rem', { lineHeight: '1rem' }],
        'sm': ['0.875rem', { lineHeight: '1.25rem' }],
        'base': ['1rem', { lineHeight: '1.5rem' }],
        'lg': ['1.125rem', { lineHeight: '1.75rem' }],
        'xl': ['1.25rem', { lineHeight: '1.75rem' }],
        '2xl': ['1.5rem', { lineHeight: '2rem' }],
        '3xl': ['1.875rem', { lineHeight: '2.25rem' }],
        '4xl': ['2.25rem', { lineHeight: '2.5rem' }],
        '5xl': ['3rem', { lineHeight: '1' }],
        '6xl': ['3.75rem', { lineHeight: '1' }],
        '7xl': ['4.5rem', { lineHeight: '1' }],
      },
      boxShadow: {
        'sm': '0 1px 2px 0 rgba(0, 0, 0, 0.05)',
        'base': '0 1px 3px 0 rgba(0, 0, 0, 0.1)',
        'md': '0 4px 6px -1px rgba(0, 0, 0, 0.1)',
        'lg': '0 10px 15px -3px rgba(0, 0, 0, 0.1)',
        'xl': '0 20px 25px -5px rgba(0, 0, 0, 0.1)',
        '2xl': '0 25px 50px -12px rgba(0, 0, 0, 0.25)',
        'luxury': '0 20px 40px rgba(0, 0, 0, 0.15)',
        'luxury-lg': '0 32px 64px rgba(0, 0, 0, 0.2)',
        'luxury-xl': '0 48px 96px rgba(0, 0, 0, 0.25)',
        'premium': '0 10px 30px rgba(220, 38, 38, 0.15)',
        'premium-lg': '0 20px 40px rgba(220, 38, 38, 0.2)',
        'inner': 'inset 0 2px 4px 0 rgba(0, 0, 0, 0.05)',
        'glass': '0 8px 32px rgba(0, 0, 0, 0.1)',
        'glass-lg': '0 16px 48px rgba(0, 0, 0, 0.15)',
      },
      animation: {
        'float': 'float 6s ease-in-out infinite',
        'pulse-slow': 'pulse 4s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'shimmer': 'shimmer 2s infinite',
        'slideInUp': 'slideInUp 0.8s ease-out',
        'slideInDown': 'slideInDown 0.8s ease-out',
        'fadeInUp': 'fadeInUp 0.8s ease-out',
        'glow': 'glow 2s ease-in-out infinite alternate',
        'tilt': 'tilt 0.3s ease-out',
        'reveal': 'reveal 0.8s ease-out',
        'parallax': 'parallax 0.5s ease-out',
        'bounce-slow': 'bounce 2s infinite',
        'spin-slow': 'spin 20s linear infinite',
        'ping-slow': 'ping 3s cubic-bezier(0, 0, 0.2, 1) infinite',
        'float-icon': 'float-icon 4s ease-in-out infinite',
        'swing': 'swing 3s ease-in-out infinite',
        'flip': 'flip 0.6s ease-in-out',
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-20px)' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-1000px 0' },
          '100%': { backgroundPosition: '1000px 0' },
        },
        slideInUp: {
          '0%': { transform: 'translateY(30px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        slideInDown: {
          '0%': { transform: 'translateY(-30px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        fadeInUp: {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        glow: {
          '0%': { boxShadow: '0 0 20px rgba(220, 38, 38, 0.5)' },
          '100%': { boxShadow: '0 0 40px rgba(220, 38, 38, 0.8)' },
        },
        tilt: {
          '0%': { transform: 'perspective(1000px) rotateX(0deg) rotateY(0deg)' },
          '100%': { transform: 'perspective(1000px) rotateX(-5deg) rotateY(5deg)' },
        },
        reveal: {
          '0%': { opacity: '0', transform: 'translateY(50px) scale(0.9)' },
          '100%': { opacity: '1', transform: 'translateY(0) scale(1)' },
        },
        parallax: {
          '0%': { transform: 'translateY(20px)' },
          '100%': { transform: 'translateY(0)' },
        },
        'float-icon': {
          '0%, 100%': { transform: 'translateY(0px) rotate(0deg)' },
          '50%': { transform: 'translateY(-15px) rotate(2deg)' },
        },
        swing: {
          '0%, 100%': { transform: 'rotate(0deg)' },
          '25%': { transform: 'rotate(3deg)' },
          '75%': { transform: 'rotate(-3deg)' },
        },
        flip: {
          '0%': { transform: 'perspective(400px) rotateY(0)' },
          '100%': { transform: 'perspective(400px) rotateY(360deg)' },
        },
      },
      backgroundImage: {
        'gradient-gold': 'linear-gradient(135deg, #EAB308 0%, #FCD34D 100%)',
        'gradient-spice': 'linear-gradient(135deg, #DC2626 0%, #EF4444 100%)',
        'gradient-dark-overlay': 'linear-gradient(135deg, rgba(0,0,0,0.7) 0%, rgba(0,0,0,0.5) 100%)',
        'gradient-light-overlay': 'linear-gradient(135deg, rgba(220,38,38,0.8) 0%, rgba(245,158,11,0.5) 100%)',
        'gradient-saffron': 'linear-gradient(135deg, #F59E0B 0%, #EAB308 100%)',
        'gradient-premium': 'linear-gradient(135deg, #DC2626 0%, #78350F 100%)',
        'gradient-radial-saffron': 'radial-gradient(circle, rgba(245, 158, 11, 0.1) 0%, transparent 70%)',
      },
      spacing: {
        '72': '18rem',
        '80': '20rem',
        '96': '24rem',
        '128': '32rem',
      },
      backdropBlur: {
        'xs': '2px',
        'sm': '4px',
      },
      opacity: {
        '55': '0.55',
      },
      transitionDuration: {
        '2000': '2000ms',
        '3000': '3000ms',
      },
    },
  },
  plugins: [],
}
